export const SETS_STORAGE_KEY = 'lexiro_sets_data'
export const SESSION_STORAGE_KEY = 'lexiro_session_data'
export const LEARNING_STORAGE_KEY = 'lexiro_learning_data'
export const DICTIONARY_CACHE_KEY = 'lexiro_dictionary_cache'
export const AI_SETTINGS_KEY = 'lexiro_ai_settings'
export const LIBRARY_STORAGE_KEY = 'lexiro_library_data'
