/** Common irregular forms used to validate generated answer spans, not to generate distractors. */
export const IRREGULAR_WORD_FORMS: Readonly<Record<string, string>> = {
  be: "am is are was were been being",
  do: "does did done doing",
  go: "goes went gone going",
  have: "has had having",
  take: "takes took taken taking",
  make: "makes made making",
  get: "gets got gotten getting",
  run: "runs ran running",
  come: "comes came coming",
  become: "becomes became becoming",
  begin: "begins began begun beginning",
  break: "breaks broke broken breaking",
  bring: "brings brought bringing",
  build: "builds built building",
  buy: "buys bought buying",
  catch: "catches caught catching",
  choose: "chooses chose chosen choosing",
  drink: "drinks drank drunk drinking",
  drive: "drives drove driven driving",
  eat: "eats ate eaten eating",
  fall: "falls fell fallen falling",
  feel: "feels felt feeling",
  find: "finds found finding",
  fly: "flies flew flown flying",
  forget: "forgets forgot forgotten forgetting",
  give: "gives gave given giving",
  grow: "grows grew grown growing",
  hear: "hears heard hearing",
  hold: "holds held holding",
  keep: "keeps kept keeping",
  know: "knows knew known knowing",
  leave: "leaves left leaving",
  lose: "loses lost losing",
  meet: "meets met meeting",
  read: "reads reading",
  ride: "rides rode ridden riding",
  rise: "rises rose risen rising",
  say: "says said saying",
  see: "sees saw seen seeing",
  sell: "sells sold selling",
  send: "sends sent sending",
  set: "sets setting",
  sit: "sits sat sitting",
  speak: "speaks spoke spoken speaking",
  spend: "spends spent spending",
  stand: "stands stood standing",
  swim: "swims swam swum swimming",
  teach: "teaches taught teaching",
  tell: "tells told telling",
  think: "thinks thought thinking",
  understand: "understands understood understanding",
  wear: "wears wore worn wearing",
  win: "wins won winning",
  write: "writes wrote written writing",
  lie: "lies lay lain lied lying",
  lay: "lays laid laying",
  lead: "leads led leading",
  let: "lets letting",
  put: "puts putting",
  cut: "cuts cutting",
  good: "better best",
  well: "better best",
  bad: "worse worst",
  far: "farther further farthest furthest",
  little: "less least",
  many: "more most",
  much: "more most",
  man: "men",
  woman: "women",
  child: "children",
  person: "people",
  tooth: "teeth",
  foot: "feet",
  mouse: "mice",
  goose: "geese",
};
