// 解說只描述公開契約與目前行為；private prompt 不進此模組。
const step = (title, text, layer, path, handoff) => ({title,text,layer,paths:[path],handoff});
const flow = (id,title,group,summary,steps,notes=[]) => ({id,title,group,section:'',summary,notes,nodes:steps,edges:steps.slice(1).map((_,i)=>({from:i,to:i+1,label:steps[i].handoff,async:steps[i+1].layer==='async'}))});
export const groups=['程式架構','資料模型','使用者操作','AI 生成','管理員操作','設定與政策','自動化與時間','頁面入口','原碼與盤點'];
export const flows=[
  flow('overview','整個專案：教材到學習結果','程式架構','教材先存在本機，練習共享詞義身份；登入後同步，AI 另由 Worker 處理。',[
    step('畫面接收操作','今天、教材、題庫、練習與我的，使用同一組 domain store。','browser','app/app/layout.tsx','已驗證操作與目前帳號'),
    step('Store 排入修改','Library／learning／preferences 的 mutation queue 讀取最新狀態，避免兩次修改互蓋。','browser','src/lib/mutation-queue.ts','新的 canonical state'),
    step('IndexedDB 正式保存','Library 寫 changed records 和 manifest，最後 publish head；learning 另存單一 blob。','database','src/lib/library-repository.ts','已保存結果與 dirty refs'),
    step('畫面採用結果','Store 保存成功才採正式資料；失敗保留編輯和重試。練習必須完成保存才能前進。','browser','stores/library-store.ts','未送出的 journal version'),
    step('同步是另一條工作','登入且連線後 reconcile Firestore。AI 生成走另一個 Worker，不負責這筆教材保存。','async','stores/cloud-store.ts','完成'),
  ],['本機資料、Firestore 副本與 D1 計費是三個不同儲存邊界。']),
  flow('architecture-ai','AI 與公開前端的邊界','程式架構','來源資料進 Worker，模型輸出回前端校對，加入才保存教材。',[
    step('來源與公開契約','Task builder 只傳 raw／sources／kind／model／tier／session，不含 private instruction。','browser','src/lib/ai/tasks.ts','Firebase-authenticated 請求'),
    step('Worker 身分與輸入','ID token、Origin、模型、來源數與 cursor owner 檢查；管理員由 server 名單決定。','worker','docs/ai-api.md','可執行的來源與預留'),
    step('D1 預留與識別','原子預留一般帳號點數，來源身份與 session／模型關聯；管理員略過預留。','database','docs/ai-api.md','帶固定 prompt 的 Responses request'),
    step('供應商產生內容','Private Worker 組 prompt 和 schema；provider key 只存在 server。','external','docs/ai-api.md','文字串流與 token usage'),
    step('結算與回傳','先結算或保存 pending usage，再送終止事件；未知成本保持 null。','worker','docs/ai-api.md','可解析與校對的結果'),
    step('使用者加入教材','Parser／assembler 驗證結構，校對畫面呈現詞義；按加入才進 Library mutation。','browser','components/questions/question-generator.tsx','完成'),
  ],['Worker 原碼與 prompt 不內嵌；其版本、端點與 migration 名稱在盤點中列出。']),
  flow('architecture-sync','本機與 Firestore 如何交接','程式架構','同步以 record 和 dirty journal 為單位，server 寫入順序決定 Library merge。',[
    step('選帳號 namespace','Guest／UID 隔離；切換前等待各 store 保存，切換後才載入本機。','browser','stores/cloud-store.ts','目前帳號 state 與 journal'),
    step('拉取遠端變更','按 writtenAt 和 documentId 讀 400 筆增量，cursor 保留時間精度及同時刻文件位置。','external','src/lib/cloud-sync.ts','server-order records'),
    step('合併但保留 dirty','Remote 按 server 順序覆寫，本機未送 record 保留；修復合併後的集合關係。','browser','src/lib/cloud-records.ts','合併後保存與待送修改'),
    step('推送與清版本','每批 400 筆，deleted tombstone 表達刪除，只清本次送出的 journal version。','external','src/lib/sync-journal.ts','目前待同步數'),
    step('狀態回到畫面','Pending 清空才顯示已同步；失敗／離線保留資料與重試，不把舊帳號完成回寫新帳號。','browser','lib/sync-status.ts','完成'),
  ]),
  flow('library-save','教材保存與原子世代','使用者操作','相同詞義在不同集合共用，保存以內容 hash 減少重寫。',[
    step('編輯詞義／例句','Word editor 以最新 Library 套單字變更，計算 sense remap，不複製另一套單字。','browser','src/lib/word-edit.ts','修改後 LibraryState'),
    step('計算 record 差異','五種 records 與舊 manifest 比對，只有內容變動才寫新 hash blob。','database','src/lib/library-repository.ts','changed blobs 與 manifest'),
    step('發布 head','最後 head pointer 使新 generation 可讀；中途失敗仍保留上一代。','database','src/lib/library-repository.ts','已保存 state 與同步差異'),
    step('清理舊世代','保留上一代，其餘在 commit 後收集。Store 更新，journal 記 dirty／tombstone。','browser','stores/library-store.ts','完成'),
  ]),
  flow('folder-set','資料夾、集合與共享收錄','使用者操作','資料夾管理位置，集合管理詞義收錄；集合不是每字的一份副本。',[
    step('資料夾操作','逐層瀏覽、新增、改名、移動與刪除由 folder UI 進 Library store。','browser','components/library/folder-toolbar.tsx','folderId 與集合操作'),
    step('集合資訊與目的地','集合 metadata、移動與新增保留所選資料夾，搜尋／返回條件由 URL 維持。','browser','components/library/set-move-dialog.tsx','set／membership 變更'),
    step('共享詞義','SetMembership 選 wordKey 和 senseIds，WordEntry 的意思／例句在所有收錄處共享。','database','src/types/library.ts','正式保存'),
    step('保存後更新','Mutation queue 套最新 state、repository commit、journal 標待送。','browser','stores/library-store.ts','完成'),
  ]),
  flow('manual-edit','手動輸入與編輯草稿','使用者操作','編輯保留 revision 草稿，驗證成功才加入；保存錯誤可重試。',[
    step('填欄位','單字／詞性／中文／例句與題目各有共用 editor，先顯示實際欄位錯誤。','browser','components/library/word-editor.tsx','編輯值與原 revision'),
    step('保存操作草稿','Local flow draft 依 namespace 隔離，返回可接續，較新正式資料不直接被舊草稿覆蓋。','database','components/ai/use-resumable-draft.ts','驗證後的修改'),
    step('正式 commit','只在保存成功時採用新 Library；失敗保留內容，確認對話框執行中鎖定。','browser','components/ui/confirm-dialog.tsx','完成'),
  ]),
  flow('practice','一次練習：判分到保存','使用者操作','詞義、拼字與已存題目共用佇列，先保存學習事實才前進。',[
    step('選集合與 tasks','選題型、數量／難度和每字一義，從同一設定頁開始。','browser','components/practice/practice-setup.tsx','穩定的 entryIds 與題序'),
    step('產生練習佇列','本機詞義選項／拼字／已存題目組合；不足選項的詞義題略過。','browser','components/practice/practice-queue.ts','本題與接受答案'),
    step('回答與判定','Question／review card 顯示答案回饋；輸入法、編輯欄位與忙碌狀態不觸發切題捷徑。','browser','components/practice/use-practice-session-actions.ts','成績及必要 rating'),
    step('Learning 保存','按 sense 更新 FSRS／題型統計，await IndexedDB；失敗復原本次作答供重試。','database','stores/learning-store.ts','保存完成'),
    step('前進與結果','保存完成才能往下。結果列錯誤／略過／標記，可重新練習或線上解說。','browser','components/practice/practice-page.tsx','完成'),
  ]),
  flow('meaning','本機四選一中文詞義題','使用者操作','無模型、無網路，用教材產生可重現選項。',[
    step('取該字所有詞義','同 wordKey 的意思全部列為可接受範圍。','browser','components/practice/meaning-questions.ts','可接受的中文答案'),
    step('選三個干擾答案','排除同字、目標詞義交集及重複中文；找不到三個就不產題。','browser','components/practice/meaning-questions.ts','四個不同選項'),
    step('種子排序與保存','固定 entry ID 種子，snapshot v4 保存原選項，接續不重新亂排。','database','components/practice/use-practice-persistence.ts','使用者選擇'),
    step('判分與學習','接受任一目標意思；記 meaning:1，並依本次首次錯誤／當日複習條件決定 FSRS rating。','browser','components/practice/use-practice-session-actions.ts','完成'),
  ]),
  flow('fsrs','FSRS 到期與掌握程度','自動化與時間','以詞義保存 card，沒有瀏覽器關閉後仍跑的複習 Cron。',[
    step('到期選取','新卡或 due <= now 為到期，進度從每詞義 card 計算。','browser','src/lib/fsrs.ts','again／good'),
    step('執行 scheduler','ts-fsrs 關閉 fuzz，更新 due、stability、difficulty 與 reps／lapses。','browser','src/lib/fsrs.ts','新 CardProgress'),
    step('持久化後生效','Learning store 保存新 card；相同單字集的共享 SenseId 讀到同份排程。','database','stores/learning-store.ts','掌握與進度讀取'),
    step('統計閱讀','Stability 21 天計入掌握，lapses >=4 為難記項目；數字是程式規則。','browser','src/constants/learning.ts','完成'),
  ]),
  flow('practice-resume','中斷練習與精確接續','自動化與時間','題序、已答狀態與詞義選項都保留，接續不是新一輪計分。',[
    step('Snapshot v4','Tasks、entryIds、答案、錯題、index 和 meaningChoices 保存到 namespace localStorage。','database','src/types/session.ts','下一次恢復讀取'),
    step('檢查與 migration','恢復驗版本和教材關聯，v3 card 草稿遷移到詞義題；損壞草稿顯示處理選擇。','browser','components/practice/use-practice-persistence.ts','使用者接續選擇'),
    step('接回原題序','保留原選項、選中答案與已完成狀態，已保存學習事實不再記一次。','browser','components/practice/practice-page.tsx','完成'),
  ]),
  flow('daily','日期滾動、連續學習與歷史','自動化與時間','資料讀／寫時按日期更新，每日歷史保留 90 天。',[
    step('讀取今日統計','Learning defaults 按本機日期滾動今天的目標與完成數。','browser','src/lib/learning-defaults.ts','日期差與既有 streak'),
    step('連續日與 freeze','連續七日可取得一次，最多兩次；單次缺日可消耗一個保留 streak。','browser','src/constants/learning.ts','更新後 stats'),
    step('保留必要歷史','Daily history 只保留圖表使用欄位，90 天外清除。','database','src/lib/learning-defaults.ts','進度呈現'),
    step('進度子頁','掌握、活動與題型從保存資料計算，沒有點按次數的經驗值。','browser','components/progress/progress-page.tsx','完成'),
  ]),
  flow('sync-auto','同步 debounce 與重試','自動化與時間','待同步變更合併 3 秒，最多等待 15 秒；離線保留 journal。',[
    step('Journal 發訊號','Commit／learning／preferences 將新版本標待送。','database','src/lib/sync-journal.ts','pending event'),
    step('合併排程','Cloud store debounce 3 秒，但持續修改最多等 15 秒；pagehide／visibility 會 flush。','async','stores/cloud-store.ts','一次 sync'),
    step('有界 request','單次最多 10 秒，同步中有新修改就記 rerun；失敗最多三次自動重試。','external','src/lib/cloud-sync.ts','成功或保留 pending'),
    step('重新連線／手動','恢復連線或按同步重新 reconcile，不刷新當前練習頁。','browser','stores/cloud-store.ts','完成'),
  ]),
  flow('account-switch','登入、登出與帳號交接','使用者操作','舊帳號非同步結果不落到新帳號，所有資料先按 namespace 載入。',[
    step('Firebase session 變更','Guest 或已登入 UID 決定當前空間；AI 要已登入 token。','external','src/lib/firebase.ts','新的 UID／guest'),
    step('排空舊保存','Account queue 等 Library、learning、AI preferences 的 mutation flush。','browser','src/lib/account-data-queue.ts','安全的 namespace 切換'),
    step('切換本機資料','清舊 listener／cursor 狀態，設定 namespace 並 reload 三個 store。','database','stores/cloud-store.ts','帳號資料已就緒'),
    step('拒絕舊回應','每次保存／sync completion 驗 owner；AI 舊 request 也不套新 session。','browser','lib/managed-client.ts','完成'),
  ]),
  flow('backup','完整備份：預覽與套用','使用者操作','匯出等待保存，匯入確認後合併最新資料。',[
    step('匯出等待 queue','Backup action 固定帳號，等待目前保存再組完整 ZIP。','browser','lib/backup-actions.ts','library + learning snapshot'),
    step('ZIP v4','lexiro-backup.json 包教材與學習；匯出供使用者保管，舊完整格式拒絕。','database','src/lib/full-backup.ts','讀檔與預覽數量'),
    step('預覽後確認','預覽只保存數量／操作選擇，不保存會覆寫後續編輯的舊 Library。','browser','components/me/data-section.tsx','原帳號匯入操作'),
    step('兩段合併保存','Queue 裡合併最新教材與學習，兩段都完成才回成功；失敗可重試。','database','src/lib/learning-backup.ts','完成'),
  ]),
  flow('share','集合分享與教材匯入','使用者操作','分享一份集合格式，不包含私人計費或供應商設定。',[
    step('選教材並匯出','集合與收錄詞義／題目由 domain 組分享資料。','browser','src/lib/share.ts','set share v1'),
    step('驗證分享檔','ZIP 內 lexiro-set.json；輸入解析及大小規則與完整備份不同。','browser','src/types/backup.ts','可合併教材'),
    step('合併正式 Library','保持 canonical WordKey／SenseId，正式保存後標待同步。','database','src/lib/library-import.ts','完成'),
  ]),
  flow('ai-words','AI 建立單字與校對','AI 生成','整理來源與生成內容分開，完成成果可接續。',[
    step('來源整理與確認','文字／照片先校對清單，生成用 word／posHint／中文提示。','browser','components/library/input-organizer.tsx','結構化來源'),
    step('拆批生成','Words 每批 25 個，runner 依序執行並恢復有效部分。','browser','src/lib/ai/tasks.ts','kind words + model/session/tier'),
    step('Worker 生成與結算','來源 ID 固定，provider 回詞義／例句，終止時記用量與來源完成。','worker','docs/ai-api.md','可解析輸出'),
    step('校對結果與加入','草稿保留結果，按加入才保存；失敗保留已生成詞義供重試。','browser','components/library/word-assistant.tsx','完成'),
  ]),
  flow('ai-photo','照片整理與批次接續','AI 生成','先確認圖片再編碼，十張一批、每批單次上游請求。',[
    step('選圖與確認','可以移除／更換，再明確開始處理，尚未確認不發請求。','browser','components/library/photo-organization-ui.tsx','已確認圖片'),
    step('壓縮 WebP','長邊 1800、每張 1.5 MB。必要時由 bundled codec 產生有效 WebP。','browser','lib/word-photo.ts','每批最多十張 base64'),
    step('單次批次請求','POST /organize text/plain，以 X-AI-Model、X-Session-Id 帶模型／身份，Worker 一次送多圖。','worker','docs/ai-api.md','lines 文字結果'),
    step('依序合併成果','完成批次保留，失敗／取消可續未完成部分，整理後仍校對來源。','browser','components/library/input-organizer.tsx','完成'),
  ],['結構驗證不等於自動證明來源語意，相關詞仍需校對。']),
  flow('ai-questions','AI 題目與確切 answer span','AI 生成','模型寫內容，assembler 檢查與挖空，不用形態字典假稱已證明語意。',[
    step('選集合及題型','取該集收錄詞義，題型按學測格式定義。','browser','components/questions/question-generator.tsx','QuestionSource refs'),
    step('拆批與模型輸出','Vocabulary／grammar 最多八來源，passage 有各自批次；Worker 固定 prompt／schema。','worker','src/lib/ai/tasks.ts','sentence／usage／answer'),
    step('組裝結構','確切 spans 各只出現一次，詞彙 answer 從 usage 開始，之後挖空與排選項。','browser','src/lib/question-assembly.ts','有效題目與未完成來源'),
    step('校對並加入','顯示目標單字與詞義，保留有效部分，可重新生成或加入 Library。','browser','components/questions/generated-question-results.tsx','完成'),
  ]),
  flow('ai-senses','補充多義與零結果','AI 生成','補的是尚未收錄的意思，上限不是必須填滿的配額。',[
    step('選字與上限','保存已有意思，要求最多一／二／三個新義。','browser','components/library/set-sense-supplement.tsx','已有詞義來源'),
    step('每批十字','Public builder 送現有 senses，Worker 和 words 共用固定 prompt cache 前綴。','worker','src/lib/ai/tasks.ts','新增或空 senses'),
    step('解析並標來源','合法新義 supplementary=true；零個意思可算完成，按字計費。','browser','src/lib/word-generation.ts','校對後的詞義'),
    step('合併正式記錄','加入最新 WordEntry，其他集合共用相同 canonical senses。','database','stores/library-store.ts','完成'),
  ]),
  flow('ai-explain','卡片介紹與錯題解說','AI 生成','Typed content 區分卡片與題目，避免捏造卡片的答錯內容。',[
    step('結果整理','Cards 準備字義介紹，questions 準備題目／實際選擇；混合保持型別。','browser','components/practice/practice-queue.ts','review／question payload'),
    step('Worker 解說','Review 介紹詞彙，question 才分析錯誤；依獨立 explanation cache 版本。','worker','docs/ai-api.md','解說文字'),
    step('結果閱讀','正常文件流呈現，StepActions 保留在所有動態結果之後。','browser','components/practice/practice-page.tsx','完成'),
  ]),
  flow('admin-account','帳號點數與額度的確認','管理員操作','只送有變欄位，後端核對閱讀版本並回實際結果。',[
    step('閱讀帳號','Cursor 帳號列表選一人，取得餘額、月額度、note、version。','browser','components/me/admin-accounts.tsx','expected 與修改'),
    step('預覽調整並確認','計算真正變動與零下限，確認對話框保持執行鎖及錯誤重試。','browser','src/lib/admin-account-adjustment.ts','PATCH expected'),
    step('D1 原子修改','Expected 不同回409。備註保留預留，資金變動等待結算；遞增 version。','database','docs/ai-api.md','canonical account'),
    step('採正式回覆','Cache 以後端回傳結果更新，草稿保留到成功；過期重新讀取。','browser','components/me/admin-accounts.tsx','完成'),
  ]),
  flow('admin-settings','新帳號方案與試用設定','管理員操作','只影響新帳號，既有月額度要走該帳號的修改流程。',[
    step('讀取設定版本','Free trial、defaultInitial、defaultMonthly 與 version；編輯草稿不被相同背景讀取覆蓋。','browser','components/me/admin-settings.tsx','expected 設定與變更'),
    step('原子 version 寫入','D1 同敘述核對版本及三欄，衝突不部分套用。','database','docs/ai-api.md','完整 canonical settings'),
    step('新帳號採初值','ensureAccount 用目前試用／新帳號設定，關閉試用時新帳號為零。','worker','docs/ai-api.md','完成'),
  ]),
  flow('admin-usage','用量、游標與未知成本','管理員操作','先對每 response 計價再彙總，未核實與未知值明確保留。',[
    step('選時間／頁面','近30天報表與 cursor history，後端只允許管理員。','browser','components/me/admin-usage.tsx','cursor query'),
    step('逐筆成本彙總','按模型、kind／tier、UID 組合；長上下文門檻按每次 response，不按月總數。','database','docs/ai-api.md','reported／pending／unavailable'),
    step('保留未知','任何成本缺漏整組保留 null，debitVerified=0 的歷史實扣另列。','browser','components/me/admin-usage.tsx','下一頁游標與實際讀數'),
    step('前後頁與重試','Opaque nextCursor，不用 offset；重新讀取不把未知當免費。','browser','components/me/use-admin-pagination.ts','完成'),
  ]),
  flow('billing-recovery','延遲 usage 與每日計費維護','自動化與時間','Worker Cron 是計費維護，與瀏覽器教材／FSRS 無關。',[
    step('終止缺 usage','先補查 stored response，仍未知就寫 pending metadata，不保存 prompt／輸出。','worker','docs/ai-api.md','待核對的 D1 record'),
    step('保留責任','有產出保留預留，取消／失敗退款；unavailable 不冒填零成本。','database','docs/ai-api.md','下次帳號 request／Cron'),
    step('有界補查','每天 UTC00:00，臺灣08:00，先 reconcile 再 maintenance；帳號請求補查最多一筆。','async','docs/ai-api.md','有有效 usage 才結算'),
    step('報表與營運','持續查不到保留 pending，需依 response ID 向供應商核對。','browser','docs/ai-api.md','完成'),
  ]),
  flow('preferences','目標與模型的待存修改','設定與政策','只保存實際編輯欄位，帳號切換後保留原帳號草稿。',[
    step('編輯目標／模型','UseAutosave 保存 partial goals 或 model，顯示忙碌／失敗／重試。','browser','components/me/use-autosave.ts','待存草稿'),
    step('Namespace draft','Version1 的 localStorage 值只含修改欄位；返回可套用或保留目前設定。','database','src/lib/preference-drafts.ts','原帳號正式保存'),
    step('Store queue 寫入','Learning goals 不蓋未編輯統計，AI preference 以 timestamp 合併雲端。','browser','stores/ai-preferences-store.ts','後續 session 使用模型'),
    step('生效邊界','新 AI session 才固定新模型；已執行的 session 保留原模型。','browser','src/lib/ai/session.ts','完成'),
  ]),
  flow('pwa-update','PWA 新版保存與接管','自動化與時間','不以網路恢復打斷練習；更新先保存再重啟。',[
    step('發現等待版本','Monitor 觀察 service worker；我的提供檢查與重啟入口。','browser','components/app-update-monitor.tsx','使用者重啟操作'),
    step('先完成保存','更新流程 flush 持久化，保存失敗顯示重試，不能略過。','database','lib/app-update.ts','SKIP_WAITING'),
    step('Controller 接管','app/sw.ts 等明確訊號啟用，client 等接管完成才 reload。','async','app/sw.ts','新 app 資產'),
    step('私人 cache 清理','登入／跨來源走 NetworkOnly，新版清舊私人 cache，保留 App 資產。','browser','src/lib/service-worker-cache.ts','完成'),
  ]),
  flow('deployment','配置、驗證與分開部署','程式架構','兩個 repo 各自驗證／部署；契約變更先發布 Worker。',[
    step('公開設定與契約','NEXT_PUBLIC 值進前端，private server keys 只進 Worker；contract repack/vendor 同步版本。','build','docs/configuration.md','lockfile 固定依賴'),
    step('前端四項 gate','Typecheck、Oxlint、Vitest、Next build，postbuild 檢查 private prompt 指紋。','build','.github/workflows/deploy.yml','同 runner Vercel prebuilt'),
    step('Rules 後發布前端','Firebase Rules/indexes 成功後，同 runner 發 Vercel production。','external','.github/workflows/deploy.yml','發布後真實驗收'),
    step('Worker 獨立發布','自己的 workflow 驗證、D1 migrations／secrets／deploy／CORS。Commit 不等於 push 或部署。','build','docs/deployment.md','完成'),
  ]),
];

export const routeSpecs={
  '/':['公開介紹與互動示範','marketing','components/marketing/landing-practice.tsx'],
  '/app':['每日任務與最近教材','learning','components/home/focus-canvas.tsx'],
  '/app/library':['資料夾與單字集瀏覽','library','stores/library-store.ts'],
  '/app/sets/new':['手動建立單字集','library','components/library/set-editor.tsx'],
  '/app/sets/new/organize':['AI 來源整理與單字生成','ai','components/library/ai-set-organizer.tsx'],
  '/app/sets/[setId]':['集合單字、題目與工具','library','stores/library-store.ts'],
  '/app/sets/[setId]/add':['手動／AI 加入單字','library','components/library/set-word-addition.tsx'],
  '/app/sets/[setId]/supplement':['補充未收錄詞義','ai','components/library/set-sense-supplement.tsx'],
  '/app/sets/[setId]/settings':['集合名稱／資料夾與metadata','library','components/library/set-metadata.tsx'],
  '/app/sets/[setId]/words/[wordKey]/edit':['詞義與例句編輯','library','components/library/word-edit-page.tsx'],
  '/app/questions':['題庫搜尋與篩選','library','components/questions/question-bank-page.tsx'],
  '/app/questions/generate':['依單字集產題與校對','ai','components/questions/question-generator.tsx'],
  '/app/questions/[questionId]/edit':['單句題編輯','library','components/questions/question-editor.tsx'],
  '/app/questions/reading/[questionId]/edit':['文章包與子題編輯','library','components/questions/reading-editor.tsx'],
  '/app/practice':['設定、作答、重練與結果','practice','components/practice/practice-page.tsx'],
  '/app/progress':['學習進度概覽','learning','components/progress/progress-page.tsx'],
  '/app/progress/coverage':['詞義掌握程度','learning','components/progress/progress-coverage.tsx'],
  '/app/progress/history':['每日活動紀錄','learning','components/progress/progress-history.tsx'],
  '/app/progress/questions':['題型表現','learning','components/progress/progress-question-performance.tsx'],
  '/app/me':['帳號與設定入口','account','components/me/me-page.tsx'],
  '/app/me/preferences':['目標、外觀與AI模型','preferences','components/me/use-autosave.ts'],
  '/app/me/plan':['點數與月額度','account','components/me/plan-section.tsx'],
  '/app/me/data':['備份與匯入','backup','components/me/data-section.tsx'],
  '/app/sync':['登入與手動同步','sync','stores/cloud-store.ts'],
  '/app/me/admin':['管理任務目錄','admin','components/me/admin-panel.tsx'],
  '/app/me/admin/accounts':['帳號游標列表','admin','components/me/admin-accounts.tsx'],
  '/app/me/admin/accounts/[uid]':['單一帳號調整','admin','components/me/admin-accounts.tsx'],
  '/app/me/admin/settings':['新帳號方案預設','admin','components/me/admin-settings.tsx'],
  '/app/me/admin/usage':['用量報表與未知成本','admin','components/me/admin-usage.tsx'],
  '/~offline':['載入失敗重試原URL','offline','components/offline-retry-button.tsx'],
};
